_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-x86_64
batch_size:
    value: 64
epochs:
    value: 10
learning_rate:
    value: 0.001
